apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-pod
spec:
  containers:
    - name: jenkins
      image: jenkins:alpine
      ports:
        - containerPort: 8080
          containerPort: 50000
      volumeMounts:
        - name: "jenkins-volume"
          mountPath: "/usr/jenkins"
          readOnly: false
  volumes:
    - name: "jenkins-volume"
