kind: Service
apiVersion: v1
metadata:
  name: "jenkins-service"
spec:
  selector:
    app: "jenkins-deployment"
  type: "LoadBalancer"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
